---
title: "Allplts"
author: "Yumo Peng"
date: "June 25, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sd<-c(2:10) #9 sigma values


phi <- c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9) #9 coefficients



#Get the data
simul_fun <- function(sigma, phi, length){
  #set seed:
  set.seed(1)
  ar1 <- arima.sim(n = length, list(ar = c(phi)), sd = sigma)
  return(ar1)
  
}

for(val in sd){
  for(val2 in phi){
    mydat <- simul_fun(val, val2, 50000)
    mydf <- data.frame("Time" = 1:50000, "AR1" = mydat)
    
    plot(mydat, pch = 19,lty = 2, ylim = c(-0.1, 0.1))
    model1 = loess(AR1~Time, data = mydf, span = 0.4)
    lines(mydf$Time,model1$fit,col='red',lty=2,lwd=2)
    model2 = loess(AR1~Time, data = mydf, span = 0.8)
    lines(mydf$Time,model2$fit,col='blue',lty=2,lwd=2)
  }
}
```



#number of points: 500, 1000, 2000, 5000, 10000, 20000, 50000
```{r}
#500 pts
sd<-c(2:10) #9 sigma values


phi <- c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9) #9 coefficients



#Get the data
simul_fun <- function(sigma, phi, length){
  #set seed:
  set.seed(1)
  ar1 <- arima.sim(n = length, list(ar = c(phi)), sd = sigma)
  return(ar1)
  
}

for(val in sd){
  for(val2 in phi){
    mydat <- simul_fun(val, val2, 500)
    mydf <- data.frame("Time" = 1:500, "AR1" = mydat)
    
    plot(mydat, pch = 19,lty = 2)
    model1 = loess(AR1~Time, data = mydf, span = 0.4)
    lines(mydf$Time,model1$fit,col='red',lty=2,lwd=2)
    model2 = loess(AR1~Time, data = mydf, span = 0.8)
    lines(mydf$Time,model2$fit,col='blue',lty=2,lwd=2)
  }
}
```



```{r}
#1000
sd<-c(2:10) #9 sigma values


phi <- c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9) #9 coefficients



#Get the data
simul_fun <- function(sigma, phi, length){
  #set seed:
  set.seed(1)
  ar1 <- arima.sim(n = length, list(ar = c(phi)), sd = sigma)
  return(ar1)
  
}

for(val in sd){
  for(val2 in phi){
    mydat <- simul_fun(val, val2, 1000)
    mydf <- data.frame("Time" = 1:1000, "AR1" = mydat)
    
    plot(mydat, pch = 19,lty = 2)
    model1 = loess(AR1~Time, data = mydf, span = 0.4)
    lines(mydf$Time,model1$fit,col='red',lty=2,lwd=2)
    model2 = loess(AR1~Time, data = mydf, span = 0.8)
    lines(mydf$Time,model2$fit,col='blue',lty=2,lwd=2)
  }
}
```

